### ISSUE TITLE
Dependencies on Microsoft.Toolkit 8.0.0-preview5

### ISSUE THREAD

**Issue by lesztar** [Noemata/FakePOS#1]
Hi Mario,
I have the following dependencies missing:
- Microsoft.Toolkit.Mvvm 8.0.0-preview5
- Microsoft.Toolkit.Uwp.UI.Controls 8.0.0-preview5
- Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 8.0.0-preview5

It does not seem the above packages come from nuget.org. Where should I download them from?

**Comment by Noemata** [comment]
Those packages come from a "special" nuget server.  It was a moving target.  I'll have to dig around to figure out what server you need to point to.  Probably best to update everything to the latest release builds, since this work was all done on preview tech.

**Comment by lesztar** [comment]
I have upgraded the release build versions of some packages and adjusted namespaces. How could I submit a pull request?

**Comment by Noemata** [comment]
Typically, in Github land, you fork the repo, make your changes, then submit a pull request along the lines of what you're familiar with.  If you haven't done this before, there are probably several youtube videos demonstrating the process.  VS2019, I think, makes this easy.  But there is a better way.  Give me a couple minutes to set up the better approach.

**Comment by Noemata** [comment]
@lesztar , you've been sent an invite to the repo.  Once you accept, you can make whatever changes you see fit directly.

**Comment by lesztar** [comment]
Thanks, @Noemata. I have also forked the FakePOS repository but I'm facing some permission issues that I need to solve locally.
